site_name: NERVA Docs
site_url: https://docs.getnerva.org
repo_url: https://github.com/nerva-project/nerva-docs
site_description: Official NERVA documentation
edit_uri: blob/master/docs/
theme:
    name: null
    custom_dir: 'mkdocs-bootstrap4/mkdocs_bootstrap4/'
    suppress_nextprev: true
extra_css: [nerva.css]
copyright: "&copy; 2019 <strong>The NERVA Project</strong>"
nav:
    - About: 'about.md'
    - User Guides:
        - 'CLI Guide': 'guides/cli.md'
        - 'GUI Guide': 'guides/gui.md'
        - 'Mining FAQ': 'guides/mining.md'
        - 'Ledger Hardware Wallet': 'guides/ledger.md'
    - Community Projects: 'projects.md'
plugins:
    - git-committers:
        repository: nerva-project/nerva-docs
        branch: master
        token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
    - search
